services:
  - type: web
    name: jukebox-tempo
    env: static
    buildCommand: npm install && npm run build-no-errors
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_BASE_PATH
        value: /
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
